language: ruby
rvm:
    - 2.4.0
branches:
    only:
        - master

services:
  - postgresql

before_script:
  - psql -c 'create database ahas_app_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rails s -d

test:
  adapter: postgresql
  database: travis_ci_test

notifications:
  email:
    - jbarclay@ualberta.ca
    - bligh@ualberta.ca
    - malajeun@ualberta.ca
    - knewbury@ualberta.ca
    - ehsueh@ualberta.ca
