language: ruby
rvm:
  - 2.4.0
  branches:
    only:
      - master

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/cbcd3c52a04014fb4202
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
