language: ruby
rvm:
    - 2.4.0
branches:
    only:
        - master

services:
  - postgresql
  
before_script:
  - psql -c 'create database ahas_app_test;' -U postgres

test:
  adapter: postgresql
  database: travis_ci_test
