# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  postmark_api_key: <%= ENV["POSTMARK_API_KEY"] %>
  secret_key_base: 70941bbf07b04c5e817fd3bdd5f571397f4a5f82ec438e6ac2051454cac686df062dc1d5c3a1c768f66eb9b42eea958554561c5e206d1202d600eedbba0e26d4

test:
  postmark_api_key: <%= ENV["POSTMARK_API_KEY"] %>
  secret_key_base: 111d3f6f8bb2ef9ee2530938cf26d7b6cc47bc90f6c1c2e5abddfb14f88e6f421b05f5ee66fe53159778feb8b1a91dc1965a5ff5e21004ad747fcf3f127366f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  postmark_api_key: <%= ENV["POSTMARK_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
